name: Scheduled Content Fetch

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:

jobs:
  fetch-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        sudo apt-get install -y libgbm-dev
        npm init -y
        npm install puppeteer

    - name: Run scraper
      run: node scraper.js

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add external_content.html
        if ! git diff --quiet --staged; then
          git commit -m "Auto-update: Content changes $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes detected"
        fi
